### ISSUE TITLE
xeus-robot-wheel request

### ISSUE THREAD

**Issue by RomaCZ** [jupyter-xeus/xeus-robot#67]
Hi,
In my company we are not allowed to install any software, so we are using [WinPython](https://github.com/winpython/winpython) (portable python) and therefore pip / wheel packages only. Conda (due to installation needs) is not option for us.
I tried google ways to convert conda package to wheel, but without luck - it might be possible but I'm not skilled enough to handle it.

Is there any chance, that you could provide wheel for robot? Or guidance how to make this conversion?
Thank you

**Comment by martinRenou** [comment]
Hello!

You're opening an issue at the right moment. I am actually working on a xeus-robot wheel since yesterday 😄 
You can follow here: https://github.com/jupyter-xeus/xeus-python-wheel/pull/76 (it's just a test PR, we might create a separate xeus-robot-wheel repository later).

I am hoping to get it done by the end of the week.

**Comment by martinRenou** [comment]
Actually, if you would like to be my official Windows wheel tester, I can provide you with it as soon as I have it. Your feedback would be really useful as I don't have a Windows machine handy.

**Comment by RomaCZ** [comment]
Wow, lucky me ;) Count me in for testing.

**Comment by martinRenou** [comment]
Thanks! Here are some wheels you can try:
- Python 3.8
https://ci.appveyor.com/api/buildjobs/e8qv3lu86ogc42yg/artifacts/xeus_robot-0.3.0-cp38-cp38-win_amd64.whl
- Python 3.7
https://ci.appveyor.com/api/buildjobs/1qyx4co8pyruxdlu/artifacts/xeus_robot-0.3.0-cp37-cp37m-win_amd64.whl

**Comment by martinRenou** [comment]
The xeus-robot wheel is now created from https://github.com/jupyter-xeus/xeus-robot-wheel
