### ISSUE TITLE
Debugger missing dependencies: [ptvsd, pydevd]

### ISSUE THREAD

**Issue by RomaCZ** [jupyter-xeus/xeus-robot#82]
Hi, I'm using Jupyter Lab on portable Python WinPython. When installing xeus-robot with pip, ptvsd and pydevd are not installed.
Once turning Debugger on, error is raised:
> Exception raised when trying to import ptvsd
> [0;31m---------------------------------------------------------------------------[0m
> [0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
> File [0;34mC:\Log\TestBot\WPy64-3810\WPy64-3810\python-3.8.10.amd64\lib\site-packages\robotframework_debug_adapter\run_robot__main__.py[0m, in [0;32mstart_communication_threads[0m:
> Line [0;34m150[0m:   [34mimport[39;49;00m [04m[36mpydevd[39;49;00m
> 
> [0;31mModuleNotFoundError[0m: No module named 'pydevd'
> [0;31m---------------------------------------------------------------------------[0m
> ModuleNotFoundError - No module named 'pydevd'
> XDEBUGGER: the debugger has started

`pip install ptvsd, pydevd` fixes this issue, so I'ques dependency for this two packages might be added.

**Comment by martinRenou** [comment]
Thanks for reporting, and sorry for not seeing your issue before. This seems to be a missing dependency on the wheel package. I will push a fix.
